# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk' 
    version: 5.0.x
    
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: devops-sample
  displayName: 'backend build'

- script: dotnet publish -c $(buildConfiguration) --self-contained true -r win-x86
  workingDirectory: devops-sample
  displayName: 'backend publish'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'devops-sample/bin/Release/net5.0/win-x86/publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/devops-sample/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'backend zip files'
